title: Ambassador Chinese
description: 
  Ambassador Chinese is the place to go for an authentic Chinese dining experience in the Houston area.
keywords: Houston, Chinese, Ambassador, Restaurant, Texas, authentic, Cantonese, Richmond, wontons, eggrolls
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
    - jekyll-money